package com.asura.finanzas.ui

// GENERATED by scripts/gen-android-strings.mjs from src/i18n/seed.ts — do not edit.
// Add or change entries in src/i18n/seed.ts, then run: npm run gen:android-strings

import androidx.compose.runtime.Composable

/** Canonical Spanish seed name -> English, mirroring the web's `seedName`. */
val SEED_EN: Map<String, String> = mapOf(
    "Efectivo" to "Cash",
    "Tarjeta de débito" to "Debit card",
    "Tarjeta de crédito" to "Credit card",
    "Cuenta de ahorro" to "Savings account",
    "Otro" to "Other",
    "Salario" to "Salary",
    "Regalo" to "Gift",
    "Intereses" to "Interest",
    "Otro ingreso" to "Other income",
    "Comida" to "Food",
    "Transporte" to "Transport",
    "Hogar" to "Home",
    "Entretenimiento" to "Entertainment",
    "Salud" to "Health",
    "Suscripciones" to "Subscriptions",
    "Otro gasto" to "Other expense",
    "Metas" to "Goals",
    "Meses sin intereses" to "Interest-free installments",
    "Inversiones" to "Investments",
    "Peso mexicano" to "Mexican peso",
    "Dólar estadounidense" to "US dollar",
)

/**
 * Localize the name of a system seed row. User-created rows (`isSystem` false)
 * and the Spanish locale return the stored name verbatim.
 */
fun seedName(name: String?, isSystem: Boolean, locale: String): String? {
    if (name == null || !isSystem || !locale.startsWith("en")) return name
    return SEED_EN[name] ?: name
}

/** Same, resolved against the language chosen in the app's own settings. */
@Composable
fun seedName(name: String?, isSystem: Boolean = true): String? =
    seedName(name, isSystem, LocalAppSettings.current.locale)
